### ISSUE TITLE
error after providing one-time-code

### ISSUE THREAD

**Issue by faroit** [hugodecasta/ZRMconnector#2]
using the following config

```json
{
    "zotero_1": {
        "remarkable_dir": "/zot",
        "remarkable_archive_dir": "bin'",
        "zotero_path": [
            {
                "type": "collection",
                "name": "RM"
            }
        ],
        "tags": {
            "me - toread": "2READ",
            "me - reading": "READING",
            "me - done": "READ"
        }
    }
}
```

resulted in the following error after providing a new one-time-code

```
❯ node .
[SYSTEM]::launch of ZRMc system v0.4.2
[CONN:zotero_1]::setup local_directories /zot
CREDENTIAL NEEDED - ReMarkable One Time Code: ixslwrza
ReMarkable credentials Error

/Users/faro/repositories/ZRMconnector/node_modules/node-fetch/lib/index.js:1461
                        reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
                               ^
FetchError: request to https://doesnotexist.remarkable.com/ failed, reason: getaddrinfo ENOTFOUND doesnotexist.remarkable.com
    at ClientRequest.<anonymous> (/Users/faro/repositories/ZRMconnector/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (node:events:365:28)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:365:28)
    at emitErrorNT (node:internal/streams/destroy:193:8)
    at emitErrorCloseNT (node:internal/streams/destroy:158:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND'
}
```

any idea?

**Comment by hugodecasta** [comment]
> using the following config
> 
> ```json
> {
>     "zotero_1": {
>         "remarkable_dir": "/zot",
>         "remarkable_archive_dir": "bin'",
>         "zotero_path": [
>             {
>                 "type": "collection",
>                 "name": "RM"
>             }
>         ],
>         "tags": {
>             "me - toread": "2READ",
>             "me - reading": "READING",
>             "me - done": "READ"
>         }
>     }
> }
> ```
> 
> resulted in the following error after providing a new one-time-code
> 
> ```
> ❯ node .
> [SYSTEM]::launch of ZRMc system v0.4.2
> [CONN:zotero_1]::setup local_directories /zot
> CREDENTIAL NEEDED - ReMarkable One Time Code: ixslwrza
> ReMarkable credentials Error
> 
> /Users/faro/repositories/ZRMconnector/node_modules/node-fetch/lib/index.js:1461
>                         reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
>                                ^
> FetchError: request to https://doesnotexist.remarkable.com/ failed, reason: getaddrinfo ENOTFOUND doesnotexist.remarkable.com
>     at ClientRequest.<anonymous> (/Users/faro/repositories/ZRMconnector/node_modules/node-fetch/lib/index.js:1461:11)
>     at ClientRequest.emit (node:events:365:28)
>     at TLSSocket.socketErrorListener (node:_http_client:447:9)
>     at TLSSocket.emit (node:events:365:28)
>     at emitErrorNT (node:internal/streams/destroy:193:8)
>     at emitErrorCloseNT (node:internal/streams/destroy:158:3)
>     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
>   type: 'system',
>   errno: 'ENOTFOUND',
>   code: 'ENOTFOUND'
> }
> ```
> 
> any idea?

reMarkable changed their auth api (2 month from now) so the library is not currently able to authenticate correctly. I'll check when i have time to fix it.

Thanks for the head up

**Comment by faroit** [comment]
@hugodecasta oh, that's sad. Your projects sounds really promising compared to the other attempts for syncing zotero and rm. Maybe it would help to rely on one of the go or python cloud clients for auth and file access?

**Comment by hugodecasta** [comment]
Yes actually I'm planning on rebuilding the project. reMarkable have made some updates on their cloud system (fixed names, new otp auth procedure)
And I learned a lot about how not to destroy your cloud data and account some stay tuned for news about a coming refactoring

**Comment by faroit** [comment]
@hugodecasta let me know if you need some help. I am interested to contribute
